version: '3'
services: 
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile.dev
    ports: 
    - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  # tests:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - .:/app
  #   command: ["npm", "run", "test"]